#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0


#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: 1.0.0

# server 所用到配置部分设置
server:
  restful:
    listenAddress: :8888

client:
  organization: Org1

  logging:
    level: info
  eventService:
    type: deliver
  cryptoconfig:
    path: ${FABRIC_ARTIFACTS}/config/crypto-config
  credentialStore:
    path: "/tmp/state-store"
    # path: ${FABRIC_ARTIFACTS}/config/state-store
    cryptoStore:
      path: /tmp/msp
  BCCSP:
    security:
     enabled: true
     default:
      provider: "GM"
     hashAlgorithm: "SHA2"
     softVerify: true
     level: 256

  tlsCerts:
    systemCertPool: false

    client:
      key:
        path: ${FABRIC_ARTIFACTS}/config/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.key
      cert:
        path: ${FABRIC_ARTIFACTS}/config/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.crt

channels:
  mychannel:
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

#      peer0.org2.example.com:
#        endorsingPeer: true
#        chaincodeQuery: true
#        ledgerQuery: true
#        eventSource: true
#      peer1.org2.example.com:
#        endorsingPeer: true
#        chaincodeQuery: true
#        ledgerQuery: true
#        eventSource: true
#
#      peer0.org3.example.com:
#        endorsingPeer: true
#        chaincodeQuery: true
#        ledgerQuery: true
#        eventSource: true
#      peer1.org3.example.com:
#        endorsingPeer: true
#        chaincodeQuery: true
#        ledgerQuery: true
#        eventSource: true


    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0

organizations:
  Org1:
    mspid: Org1MSP
    cryptoPath:  peerOrganizations/org1.example.com/users/{username}@org1.example.com/msp/

    peers:
      - peer0.org1.example.com
      - peer1.org1.example.com

#  Org2:
#    mspid: Org2MSP
#    cryptoPath:  peerOrganizations/org2.example.com/users/{username}@org2.example.com/msp/
#
#    peers:
#      - peer0.org2.example.com
#      - peer1.org2.example.com
#
#  Org3:
#    mspid: Org3MSP
#    cryptoPath:  peerOrganizations/org3.example.com/users/{username}@org3.example.com/msp/
#
#    peers:
#      - peer0.org3.example.com
#      - peer1.org3.example.com

  ordererorg:
      mspID: "OrdererOrg"

      cryptoPath: ordererOrganizations/example.com/users/{username}@example.com/msp/

orderers:
  orderer.example.com:
    url: orderer.example.com:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false

    tlsCACerts:
      path: ${FABRIC_ARTIFACTS}/config/crypto-config/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem

peers:

  peer0.org1.example.com:
    url: peer0.org1.example.com:7051
    eventUrl: peer0.org1.example.com:7053

    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false

    tlsCACerts:
      path: ${FABRIC_ARTIFACTS}/config/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

  peer1.org1.example.com:
      url: peer1.org1.example.com:8051
      eventUrl: peer1.org1.example.com:8053

      grpcOptions:
        ssl-target-name-override: peer1.org1.example.com
        keep-alive-time: 0s
        keep-alive-timeout: 20s
        keep-alive-permit: false
        fail-fast: false
        allow-insecure: false

      tlsCACerts:
        path: ${FABRIC_ARTIFACTS}/config/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

#  peer0.org2.example.com:
#    url: peer0.org2.example.com:9051
#    eventUrl: peer0.org2.example.com:9053
#
#    grpcOptions:
#      ssl-target-name-override: peer0.org2.example.com
#      keep-alive-time: 0s
#      keep-alive-timeout: 20s
#      keep-alive-permit: false
#      fail-fast: false
#      allow-insecure: false
#
#    tlsCACerts:
#      path: ${FABRIC_ARTIFACTS}/config/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem
#
#  peer1.org2.example.com:
#      url: peer1.org2.example.com:10051
#      eventUrl: peer1.org2.example.com:10053
#
#      grpcOptions:
#        ssl-target-name-override: peer1.org2.example.com
#        keep-alive-time: 0s
#        keep-alive-timeout: 20s
#        keep-alive-permit: false
#        fail-fast: false
#        allow-insecure: false
#
#      tlsCACerts:
#        path: ${FABRIC_ARTIFACTS}/config/crypto-config/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem
#
#  peer0.org3.example.com:
#    url: peer0.org3.example.com:11051
#    eventUrl: peer0.org3.example.com:11053
#
#    grpcOptions:
#      ssl-target-name-override: peer0.org3.example.com
#      keep-alive-time: 0s
#      keep-alive-timeout: 20s
#      keep-alive-permit: false
#      fail-fast: false
#      allow-insecure: false
#
#    tlsCACerts:
#      path: ${FABRIC_ARTIFACTS}/config/crypto-config/peerOrganizations/org3.example.com/tlsca/tlsca.org3.example.com-cert.pem
#
#  peer1.org3.example.com:
#      url: peer1.org3.example.com:12051
#      eventUrl: peer1.org3.example.com:12053
#
#      grpcOptions:
#        ssl-target-name-override: peer1.org3.example.com
#        keep-alive-time: 0s
#        keep-alive-timeout: 20s
#        keep-alive-permit: false
#        fail-fast: false
#        allow-insecure: false
#
#      tlsCACerts:
#        path: ${FABRIC_ARTIFACTS}/config/crypto-config/peerOrganizations/org3.example.com/tlsca/tlsca.org3.example.com-cert.pem

